parson/src/Controller/BaseController.php
<?php


namespace App\Controller;


use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

abstract  class BaseController extends AbstractController
{
    protected function getUser() : User
    {
        return parent::getUser();
    }

}

parson/src/Controller/ParsonController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ParsonController extends AbstractController
{
    /**
     * @Route("/", name="parson_home")
     */
    public function index()
    {

        return $this->render('parson/welcome.html.twig');
    }
}

parson/templates/parson/welcome.html.twig
{% extends 'base.html.twig' %}

{% block title %} Bienvenue à Parson ! {% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/home.css') }}">
{% endblock %}

{% block body %}
    <div class="col-12 p-0 m-0" >
        <div class="row">
            <div class="col-lg-5 col-md-12 col-sm-12 mt-5 py-5">

                <div class="col-12 text-center ">

                    <div class="py-5 col-12  welcome_msg ">
                        {% if is_granted('ROLE_USER') %}
                            <h1>  Bienvenue {{ app.user.fullName }} !</h1>
                            <div class="welcome">
                                <p> Trouvez un cours qui vous va le mieux </p>
                                <p> Et pourquoi pas lancez vos cours ! </p>
                                <small> N'oubliez pas que désormais vous faites parti de nous ! </small>
                            </div>
                        {% else %}
                            <h1>  Bienvenue à ParSon !</h1>
                            <div class="welcome">
                                <p> Trouvez un cours qui vous va le mieux </p>
                                <p> Et pourquoi pas lancez vos cours ! </p>
                                <a href="{{ path('app_register') }}" class="ml-2 btn btn-outline-dark btn-lg">commencer l'aventure !</a>
                            </div>
                        {% endif %}

                        <!-- <div class="btn_">
                            <a href="/register" class="btn"> Commencer ! </a>
                        </div> -->
                    </div>

                </div>

            </div>
            <div class="col-lg-7 col-md-12 col-sm-12 mt-5 py-5">

                <div class="col-12 text-center mt-0 pt-0 welcome_img">

                    <div class=" col-12 text-light">
                        <img src="{{ asset('img/parson_welcome.png') }}" alt="">
                    </div>

                </div>

            </div>
        </div>





    </div>

{% endblock %}